### ISSUE TITLE
Hoping getting more detail source code

### ISSUE THREAD

**Issue by learning310** [xiyangcai/SleepPrintNet#1]
Thanks for your contributition for sleep staging field. You done very GOOD job! 
I have a problem when I reading your code. In data preprocess, there is the type of file called 'fre_spa'. I was wonder those file are processed by using Brain Electrical Activity Mapping technical which bring it up in paper. Can you release the code about how you process raw data to get this type data.

**Comment by xiyangcai** [comment]
Hi, thank you for your interest and the preprocess code from raw data is uploaded.
